services:
  api:
    build:
      context: ../backend   # pasta do Dockerfile e package.json
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  front:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: DevOps
    ports:
      - "5432:5432"
